[profile.default]
src = "src"
out = "out"
eth-rpc-url = "https://testnet-rpc2.monad.xyz/52227f026fa8fac9e2014c58fbf5643369b3bfc6"
chain_id = 1

[profile.default.solc_settings]
optimizer = { enabled = true, runs = 200 }
metadata = { bytecodeHash = "ipfs" }

[profile.sourcify]
enabled = true
apiUrl = "https://sourcify-api-monad.blockvision.org"
browserUrl = "https://testnet.monadexplorer.com"
